version: 2

sphinx:
  configuration: python/docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: python
      extra_requirements:
        - docs
