[package]
name = "mittagleffler"
version = "2023.4.0"
edition = "2021"

[lib]
name = "mittagleffler"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
numpy = "0.18"
