# SPDX-FileCopyrightText: 2024 Alexandru Fikl <alexfikl@gmail.com>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "mittagleffler"
SPDX-PackageSupplier = "Alexandru Fikl <alexfikl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/alexfikl/mittagleffler"

[[annotations]]
path = ["Cargo.toml", "pyproject.toml", "Makefile", "README.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".gitignore", ".github/workflows/**.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["requirements.in", "requirements.txt", "requirements-dev.txt", "Cargo.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
