name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 12 * * 0'

permissions:
  contents: read

jobs:
  linux:
    name: pytest-linux-${{ matrix.target }}-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, x86]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          make install
          make test

  windows:
    name: pytest-windows-${{ matrix.target }}-${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.target }}
      - name: Run tests
        run: |
          make install
          make test

  macos:
    name: pytest-macos-${{ matrix.target }}-${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          make install
          make test
