name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    tags: [ 'v**' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '30 12 * * 0'

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: |
          pipx run build --sdist --outdir dist python
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build_wheels_linux:
    name: Build wheels (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: dtolnay/rust-toolchain@stable
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          manylinux: auto
          args: --release --out dist -m python/Cargo.toml
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-linux-${{ strategy.job-index }}
          path: dist/*.whl

  publish:
    needs: [ 'build_sdist', 'build_wheels_linux' ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
